### REST Client
@fhirurl =https://fhirworkspace593-fhirservice.fhir.azurehealthcareapis.com
@clientid =69462078-c9fb-45cd-90fa-90f1facaee41
@clientsecret =uVS8Q~UwzX7~6qsTdF.zLYLmNL9VoNWZzlIR_c4G
@tenantid =e94a7344-127e-4ba2-b995-24410a5be1de


GET https://fhirworkspace593-fhirservice.fhir.azurehealthcareapis.com/metadata


### Get access token 
# @name getAADToken 
POST https://login.microsoftonline.com/{{tenantid}}/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&resource={{fhirurl}}
&client_id={{clientid}}
&client_secret={{clientsecret}}
&scope={{fhirurl}}/.default

### Extract access token from getAADToken request
@token = {{getAADToken.response.body.access_token}}


### GET Patient 
GET {{fhirurl}}/Patient
Authorization: Bearer {{token}}

POST {{fhirurl}}/Patient
Authorization: Bearer {{token}}
Content-Type: application/fhir+json

### GET Patient 
{
  "resourceType": "Patient",
  "name": [
    {
      "use": "official",
      "family": "Lopez",
      "given": ["Jose"]
    }
  ],
  "gender": "male",
  "birthDate": "1985-05-20"
}


### GET Patient 
GET {{fhirurl}}/Patient/57866137-220c-46d8-ba97-188d51448c0a
Authorization: Bearer {{token}}